// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for OrderStatus.
const (
	CANCELLED OrderStatus = "CANCELLED"
	CREATED   OrderStatus = "CREATED"
	PAID      OrderStatus = "PAID"
	SHIPPED   OrderStatus = "SHIPPED"
)

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Items  []OrderItem `json:"items"`
	UserId int64       `json:"userId"`
}

// Order defines model for Order.
type Order struct {
	CreatedAt  time.Time   `json:"createdAt"`
	Id         int64       `json:"id"`
	Status     OrderStatus `json:"status"`
	TotalPrice *int64      `json:"totalPrice,omitempty"`
	UserId     int64       `json:"userId"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Price     int64 `json:"price"`
	ProductId int64 `json:"productId"`
	Quantity  int   `json:"quantity"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest
