baseURL = 'https://kirya522.github.io/distributed-systems-course/'
languageCode = 'ru-ru'
title = 'Паттерны и компоненты современных распределенных систем'
theme = 'techdoc'
enableGitInfo = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'