baseURL = 'https://kirya522.github.io/distributed-systems-course/'
languageCode = 'ru-ru'
languageName = "Russian"
defaultContentLanguage = "ru"
enableEmoji = true
enableRobotsTXT = false
title = 'Курс: паттерны распределенных систем'
theme = ['hugo-book']
enableGitInfo = true

# browser tab name
description = "Бесплатный, open-source курс по паттернам и компонентам современных распределенных систем"

[params]
  BookTheme = 'auto'
  BookLogo = 'logo.png'
  BookFavicon = 'favicon.ico'
  BookSection = '*'
  BookPortableLinks = true
  BookRepo = 'https://github.com/kirya522/distributed-systems-course'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'

[params.author]
name = "Кирилл Грищук"
email = "kirya522@gmail.com"


[caches]
  [caches.images]
    dir = ':cacheDir/images'

#analytics
[services]
[services.googleAnalytics]
  id = "UA-158616174-1"
